// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILbOVKTuuew2GKYnrcMGQ72uB4TQFMsg',
    appId: '1:603443413941:web:85e24da059fb89562c0ffc',
    messagingSenderId: '603443413941',
    projectId: 'dalel-b4b53',
    authDomain: 'dalel-b4b53.firebaseapp.com',
    storageBucket: 'dalel-b4b53.appspot.com',
    measurementId: 'G-NK4YR6PYDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDlgqla_sv4J8lq5pDB9fRHGbSCiWzF0',
    appId: '1:603443413941:android:cae84403b326acf62c0ffc',
    messagingSenderId: '603443413941',
    projectId: 'dalel-b4b53',
    storageBucket: 'dalel-b4b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqcgYPPyRvf2U7K9UvC3JLt2VI5-aAFPU',
    appId: '1:603443413941:ios:733a9dad0a8e1ce62c0ffc',
    messagingSenderId: '603443413941',
    projectId: 'dalel-b4b53',
    storageBucket: 'dalel-b4b53.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqcgYPPyRvf2U7K9UvC3JLt2VI5-aAFPU',
    appId: '1:603443413941:ios:9e5e9c1fa9acfe912c0ffc',
    messagingSenderId: '603443413941',
    projectId: 'dalel-b4b53',
    storageBucket: 'dalel-b4b53.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
